"""Initial migration.

Revision ID: 1f76479bc982
Revises: 
Create Date: 2025-04-21 02:01:24.907572

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f76479bc982'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('body_measurement', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_body_measurement_created_at'), ['created_at'], unique=False)

    with op.batch_alter_table('exercise', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_exercise_created_at'), ['created_at'], unique=False)

    with op.batch_alter_table('share', schema=None) as batch_op:
        batch_op.alter_column('scope',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               existing_nullable=False)
        batch_op.create_index(batch_op.f('ix_share_created_at'), ['created_at'], unique=False)
        batch_op.create_unique_constraint('uq_share_relationship', ['sender_id', 'receiver_id', 'scope'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('share', schema=None) as batch_op:
        batch_op.drop_constraint('uq_share_relationship', type_='unique')
        batch_op.drop_index(batch_op.f('ix_share_created_at'))
        batch_op.alter_column('scope',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=False)

    with op.batch_alter_table('exercise', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exercise_created_at'))

    with op.batch_alter_table('body_measurement', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_body_measurement_created_at'))

    # ### end Alembic commands ###
