"""Goal remove current_value

Revision ID: 3c385d630279
Revises: db2c722e4f4d
Create Date: 2025-05-11 01:07:08.422821

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c385d630279'
down_revision = 'db2c722e4f4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('goal', schema=None) as batch_op:
        batch_op.drop_column('current_value')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('goal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_value', sa.FLOAT(), nullable=False))

    # ### end Alembic commands ###
