"""Add unit to CalorieIntake

Revision ID: 4cb763e73cc8
Revises: c80d79af447b
Create Date: 2025-05-08 17:02:35.487703

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "4cb763e73cc8"
down_revision = "c80d79af447b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("calorie_intake", schema=None) as batch_op:
        batch_op.add_column(sa.Column("unit", sa.Text(), nullable=True))

    op.execute("UPDATE calorie_intake SET unit = 'kcal' WHERE unit IS NULL")

    with op.batch_alter_table("calorie_intake", schema=None) as batch_op:
        batch_op.alter_column("unit", nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("calorie_intake", schema=None) as batch_op:
        batch_op.drop_column("unit")

    # ### end Alembic commands ###
