"""Unify the name of the created date field, remove some relationship

Revision ID: 873bcf1e8120
Revises: f196ae8e29d1
Create Date: 2025-05-13 11:26:14.664147

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "873bcf1e8120"
down_revision = "f196ae8e29d1"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("achievement", schema=None) as batch_op:
        batch_op.add_column(sa.Column("created_at", sa.DateTime(), nullable=True))

    with op.batch_alter_table("achievement", schema=None) as batch_op:
        op.execute("UPDATE achievement SET created_at = achieved_at")
        batch_op.alter_column("created_at", nullable=False)

        batch_op.create_foreign_key(
            "fk_achievement_user_id", "user", ["user_id"], ["id"], ondelete="CASCADE"
        )
        batch_op.drop_column("achieved_at")

    with op.batch_alter_table("body_measurement", schema=None) as batch_op:
        batch_op.create_foreign_key(
            "fk_body_measurement_user_id",
            "user",
            ["user_id"],
            ["id"],
            ondelete="CASCADE",
        )

    with op.batch_alter_table("calorie_intake", schema=None) as batch_op:
        batch_op.create_foreign_key(
            "fk_calorie_intake_user_id", "user", ["user_id"], ["id"], ondelete="CASCADE"
        )

    with op.batch_alter_table("exercise", schema=None) as batch_op:
        batch_op.create_foreign_key(
            "fk_exercise_user_id", "user", ["user_id"], ["id"], ondelete="CASCADE"
        )

    with op.batch_alter_table("goal", schema=None) as batch_op:
        batch_op.create_foreign_key(
            "fk_goal_user_id", "user", ["user_id"], ["id"], ondelete="CASCADE"
        )

    with op.batch_alter_table("scheduled_exercise", schema=None) as batch_op:
        batch_op.create_foreign_key(
            "fk_scheduled_exercise_user_id",
            "user",
            ["user_id"],
            ["id"],
            ondelete="CASCADE",
        )

    with op.batch_alter_table("share", schema=None) as batch_op:
        batch_op.create_foreign_key(
            "fk_share_sender_id", "user", ["sender_id"], ["id"], ondelete="CASCADE"
        )
        batch_op.create_foreign_key(
            "fk_share_receiver_id", "user", ["receiver_id"], ["id"], ondelete="CASCADE"
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("share", schema=None) as batch_op:
        batch_op.drop_constraint("fk_share_sender_id", type_="foreignkey")
        batch_op.drop_constraint("fk_share_receiver_id", type_="foreignkey")
        batch_op.create_foreign_key(None, "user", ["sender_id"], ["id"])
        batch_op.create_foreign_key(None, "user", ["receiver_id"], ["id"])

    with op.batch_alter_table("scheduled_exercise", schema=None) as batch_op:
        batch_op.drop_constraint("fk_scheduled_exercise_user_id", type_="foreignkey")
        batch_op.create_foreign_key(None, "user", ["user_id"], ["id"])

    with op.batch_alter_table("goal", schema=None) as batch_op:
        batch_op.drop_constraint("fk_goal_user_id", type_="foreignkey")
        batch_op.create_foreign_key(None, "user", ["user_id"], ["id"])

    with op.batch_alter_table("exercise", schema=None) as batch_op:
        batch_op.drop_constraint("fk_exercise_user_id", type_="foreignkey")
        batch_op.create_foreign_key(None, "user", ["user_id"], ["id"])

    with op.batch_alter_table("calorie_intake", schema=None) as batch_op:
        batch_op.drop_constraint("fk_calorie_intake_user_id", type_="foreignkey")
        batch_op.create_foreign_key(None, "user", ["user_id"], ["id"])

    with op.batch_alter_table("body_measurement", schema=None) as batch_op:
        batch_op.drop_constraint("fk_body_measurement_user_id", type_="foreignkey")
        batch_op.create_foreign_key(None, "user", ["user_id"], ["id"])

    with op.batch_alter_table("achievement", schema=None) as batch_op:
        batch_op.add_column(sa.Column("achieved_at", sa.DATETIME(), nullable=False))
        batch_op.drop_constraint("fk_achievement_user_id", type_="foreignkey")
        batch_op.create_foreign_key(None, "user", ["user_id"], ["id"])
        batch_op.drop_column("created_at")

    # ### end Alembic commands ###
