"""Add share_uuid to Achievement with named unique constraint

Revision ID: 8e05cee26126
Revises: 
Create Date: 2025-04-20 12:59:22.201745

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e05cee26126'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('achievement', schema=None) as batch_op:
        batch_op.add_column(sa.Column('share_uuid', sa.String(length=100), nullable=True))
        batch_op.create_unique_constraint('uq_achievement_share_uuid', ['share_uuid'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('achievement', schema=None) as batch_op:
        batch_op.drop_constraint('uq_achievement_share_uuid', type_='unique')
        batch_op.drop_column('share_uuid')

    # ### end Alembic commands ###
