"""add user avatar,date_of_birth,sex

Revision ID: ce94f8f38c60
Revises: 1f76479bc982
Create Date: 2025-05-02 00:15:44.327706

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce94f8f38c60'
down_revision = '1f76479bc982'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar', sa.String(length=256), nullable=True))
        batch_op.add_column(sa.Column('date_of_birth', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('sex', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('sex')
        batch_op.drop_column('date_of_birth')
        batch_op.drop_column('avatar')

    # ### end Alembic commands ###
