"""empty message

Revision ID: d2b511571f45
Revises: cdb6a1336b3b
Create Date: 2025-05-07 18:30:52.522994

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2b511571f45'
down_revision = 'cdb6a1336b3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('goal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('exercise_type', sa.Enum('CYCLING', 'RUNNING', 'SWIMMING', 'WEIGHTLIFTING', 'YOGA', name='exercisetype'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('goal', schema=None) as batch_op:
        batch_op.drop_column('exercise_type')

    # ### end Alembic commands ###
