"""update Goal

Revision ID: d4dc492a6e40
Revises: ce94f8f38c60
Create Date: 2025-05-07 11:51:41.712102

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4dc492a6e40'
down_revision = 'ce94f8f38c60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('goal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('exercise_type', sa.Enum('CYCLING', 'RUNNING', 'SWIMMING', 'WEIGHTLIFTING', 'YOGA', name='exercisetype'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('goal', schema=None) as batch_op:
        batch_op.drop_column('exercise_type')

    # ### end Alembic commands ###
