"""remove unit

Revision ID: dcaa853a8df5
Revises: 3c385d630279
Create Date: 2025-05-11 01:57:05.295834

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dcaa853a8df5'
down_revision = '3c385d630279'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('body_measurement', schema=None) as batch_op:
        batch_op.drop_column('unit')

    with op.batch_alter_table('calorie_intake', schema=None) as batch_op:
        batch_op.drop_column('unit')

    with op.batch_alter_table('goal', schema=None) as batch_op:
        batch_op.drop_column('unit')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('goal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unit', sa.VARCHAR(length=32), nullable=True))

    with op.batch_alter_table('calorie_intake', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unit', sa.TEXT(), nullable=False))

    with op.batch_alter_table('body_measurement', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unit', sa.TEXT(), nullable=False))

    # ### end Alembic commands ###
