"""Add achieved to Goal to reduce database queries

Revision ID: f196ae8e29d1
Revises: dcaa853a8df5
Create Date: 2025-05-11 13:39:10.080372

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "f196ae8e29d1"
down_revision = "dcaa853a8df5"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("goal", schema=None) as batch_op:
        batch_op.add_column(sa.Column("achieved", sa.Boolean(), nullable=True))

    op.execute("UPDATE goal SET achieved = false WHERE achieved IS NULL")

    with op.batch_alter_table("goal", schema=None) as batch_op:
        batch_op.alter_column("achieved", nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("goal", schema=None) as batch_op:
        batch_op.drop_column("achieved")

    # ### end Alembic commands ###
